{
  description = "My Home Manager Flake";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-26.05";

    home-manager = {
      url = "github:nix-community/home-manager/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    nix-darwin = {
      url = "github:nix-darwin/nix-darwin/nix-darwin-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    agenix.url = "github:ryantm/agenix";
    nvf.url = "github:notashelf/nvf";
    nixgl.url = "github:nix-community/nixGL";
    workmux = {
      url = "github:raine/workmux";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    flake-utils.url = "github:numtide/flake-utils";
  };

  # use nix-command and flakes experimental features
  nixConfig = {
    extra-experimental-features = ["nix-command" "flakes"];
  };

  outputs = {
    self,
    nixpkgs,
    home-manager,
    nix-darwin,
    agenix,
    nvf,
    nixgl,
    workmux,
    flake-utils,
    ...
  }: let
    linux_system = "x86_64-linux";
    user = "alv";
    mac_system = "aarch64-darwin";
    # TODO: add your user and host-name
    mac_host = "Alvaros-MacBook-Pro";
    shared-inputs = [
      nvf.homeManagerModules.default
      ./home/common/default.nix
    ];
    linux-inputs = shared-inputs ++ [agenix.homeManagerModules.default];
  in
    {
      # home-manager config
      homeConfigurations = {
        # Configuration for your main Linux Wayland machine
        ${user} = home-manager.lib.homeManagerConfiguration {
          pkgs = nixpkgs.legacyPackages.${linux_system};
          extraSpecialArgs = {
            inherit nixgl workmux;
          };
          modules =
            linux-inputs
            ++ [
              ./home/linux.nix
            ];
        };
      };

      # NixOS config
      nixosConfigurations = {
        nixos-vm = nixpkgs.lib.nixosSystem {
          system = linux_system;
          modules = [
            ./hosts/nixos-vm/configuration.nix

            # INFO: You can optionally import your HM right into the VM,
            # consider when proting to NixOs
            home-manager.nixosModules.home-manager
            {
              home-manager = {
                useGlobalPkgs = true;
                useUserPackages = true;
                sharedModules = [
                  {
                    _module.args = {
                      inherit nixgl workmux;
                    };
                  }
                ];
                users.${user} = {
                  imports =
                    linux-inputs
                    ++ [
                      ./home/linux.nix
                    ];
                };
              };
            }
          ];
        };
      };

      darwinConfigurations.${mac_host} = nix-darwin.lib.darwinSystem {
        system = mac_system; # Apple Silicon M1/M2/M3
        specialArgs = {inherit user;};
        modules = [
          ./hosts/macos/system-configuration.nix
          home-manager.darwinModules.home-manager
          {
            home-manager = {
              sharedModules = [
                {
                  _module.args = {
                    inherit workmux;
                  };
                }
              ];
              users.${user} = {
                imports = shared-inputs ++ [./home/macos.nix]; # Mix in Mac-specific user settings
              };
            };
          }
        ];
      };
    }
    # per-system outputs generated by flake-utils
    // flake-utils.lib.eachSystem [linux_system mac_system "aarch64-linux"] (system: {
      devShells.default = nixpkgs.legacyPackages.${system}.mkShell {
        name = "home-manager-dev";
        shellHook = ''
          echo "Welcome to the home-manager development shell!"
          echo "To apply your configuration, run: home-manager switch --flake ."
        '';
      };

      checks =
        if system == linux_system
        then {
          hm-alv = self.homeConfigurations.${user}.activationPackage;
          nixos-vm = self.nixosConfigurations."nixos-vm".config.system.build.toplevel;
        }
        else if system == mac_system
        then {
          darwin-system = self.darwinConfigurations.${mac_host}.system;
        }
        else {};
    });
}
