name: Dotfiles Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  flake-check:                      # This is the job ID
    name: flake check               # This is the friendly display name
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        # Note: You don't need the 'include' block here since it just duplicates your matrix OS list
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check
